version: '3.1'
# env_file: ./.env

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080